CREATE DATABASE IF NOT EXISTS todo_log
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE todo_log;

CREATE TABLE IF NOT EXISTS query_log (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    sql TEXT NOT NULL,
    dateime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
